
# SEO settings
title: "Open Data Standards"
title2: " Project" # default: ""
description: "Just another minimalist Jekyll theme for technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://heiswayi.github.io/thinkspace # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "hnbloggithub"
twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Andrew Yaspan"
  job      : "Computational Analysis and Public Policy Student"
  bio      : "This is in an effort to understand the value of open data standards for open city data."
  thumb    : /images/author.jpg
  email    : ayaspan@sunlightfoundation.com
  url      : https://opencitystandards.github.io
  github   : http://github.com/aycrazy
  twitter  : http://twitter.com/andrewyaspan

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@andrewyaspan"

#api keys

plugins:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
