
# SEO settings
title: "Open Data Standards"
title2: " Project" # default: ""
description: "A catalog of projects that demonstrate the value of open data standards"
keywords: "Jekyll, open, data, sunlight, standards, free, civic, innovation, engagement, technology, tech"
url: http://heiswayi.github.io/thinkspace # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/aycrazy/open_data_standards_project
twitter_username: "andrewyaspan"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Andrew Yaspan"
  job      : "Computational Analysis and Public Policy Student"
  bio      : "I am an Sunlight Foundation Open Cities Fellow who has created a portfolio of projects to understand and try to demonstrate
  the value of open data standards.  Some can be viewed right here on this site!"
  thumb    : /images/author.jpg
  email    : ayaspan@sunlightfoundation.com
  url      : https://opencitystandards.github.io
  github   : http://github.com/aycrazy
  twitter  : http://twitter.com/andrewyaspan

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@andrewyaspan"

#api keys

plugins:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
